name: CI

on:
  pull_request_target:
    types: [opened, reopened]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: App verification
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'    
